import { Hospital } from './types';

export const ALL_SPECIALTIES = [
  '응급의학과', '신경외과', '흉부외과', '심장내과', '정형외과',
  '일반외과', '신경과', '소아청소년과', '산부인과', '비뇨의학과',
  '성형외과', '안과', '이비인후과', '피부과', '영상의학과',
];

export const ALL_FACILITIES = [
  'CT', 'MRI', '혈관조영술', '인공심폐기', '응급수술실',
  '외상소생실', '신생아집중치료실', '화상치료실', '고압산소치료기',
];

export const mockHospitals: Hospital[] = [
  {
    id: 'snuh',
    name: '서울대학교병원',
    lat: 37.5796,
    lng: 126.9990,
    address: '서울특별시 종로구 대학로 101',
    phone: '02-2072-2114',
    availableBeds: 12,
    totalBeds: 45,
    congestionLevel: 'medium',
    availableSpecialties: ['응급의학과', '신경외과', '흉부외과', '심장내과', '정형외과', '일반외과', '신경과', '소아청소년과'],
    specialists: { '응급의학과': true, '신경외과': true, '흉부외과': true, '심장내과': true, '정형외과': true, '일반외과': true, '신경과': true, '소아청소년과': true },
    operatingRooms: { total: 4, available: 2 },
    facilities: ['CT', 'MRI', '혈관조영술', '인공심폐기', '응급수술실', '외상소생실'],
    isL2Registered: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'severance',
    name: '세브란스병원',
    lat: 37.5622,
    lng: 126.9407,
    address: '서울특별시 서대문구 연세로 50-1',
    phone: '02-2228-0114',
    availableBeds: 8,
    totalBeds: 38,
    congestionLevel: 'high',
    availableSpecialties: ['응급의학과', '신경외과', '심장내과', '정형외과', '일반외과', '신경과', '산부인과'],
    specialists: { '응급의학과': true, '신경외과': true, '심장내과': true, '정형외과': true, '일반외과': true, '신경과': true, '산부인과': true },
    operatingRooms: { total: 3, available: 0 },
    facilities: ['CT', 'MRI', '혈관조영술', '인공심폐기', '응급수술실'],
    isL2Registered: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'samsung',
    name: '삼성서울병원',
    lat: 37.4881,
    lng: 127.0855,
    address: '서울특별시 강남구 일원로 81',
    phone: '02-3410-2114',
    availableBeds: 15,
    totalBeds: 50,
    congestionLevel: 'low',
    availableSpecialties: ['응급의학과', '신경외과', '흉부외과', '심장내과', '정형외과', '일반외과', '신경과', '소아청소년과', '산부인과'],
    specialists: { '응급의학과': true, '신경외과': true, '흉부외과': true, '심장내과': true, '정형외과': true, '일반외과': true, '신경과': true, '소아청소년과': true, '산부인과': true },
    operatingRooms: { total: 5, available: 3 },
    facilities: ['CT', 'MRI', '혈관조영술', '인공심폐기', '응급수술실', '외상소생실', '신생아집중치료실'],
    isL2Registered: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'asan',
    name: '서울아산병원',
    lat: 37.5270,
    lng: 127.1085,
    address: '서울특별시 송파구 올림픽로43길 88',
    phone: '02-3010-3114',
    availableBeds: 18,
    totalBeds: 55,
    congestionLevel: 'low',
    availableSpecialties: ['응급의학과', '신경외과', '흉부외과', '심장내과', '정형외과', '일반외과', '신경과', '소아청소년과', '비뇨의학과'],
    specialists: { '응급의학과': true, '신경외과': true, '흉부외과': true, '심장내과': true, '정형외과': true, '일반외과': true, '신경과': true, '소아청소년과': true, '비뇨의학과': true },
    operatingRooms: { total: 5, available: 2 },
    facilities: ['CT', 'MRI', '혈관조영술', '인공심폐기', '응급수술실', '외상소생실', '화상치료실'],
    isL2Registered: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'catholic',
    name: '서울성모병원',
    lat: 37.5015,
    lng: 127.0049,
    address: '서울특별시 서초구 반포대로 222',
    phone: '02-2258-5114',
    availableBeds: 6,
    totalBeds: 30,
    congestionLevel: 'high',
    availableSpecialties: ['응급의학과', '심장내과', '정형외과', '일반외과', '산부인과'],
    specialists: { '응급의학과': true, '심장내과': true, '정형외과': true, '일반외과': true, '산부인과': true },
    operatingRooms: { total: 3, available: 1 },
    facilities: ['CT', 'MRI', '혈관조영술', '응급수술실'],
    isL2Registered: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'korea-anam',
    name: '고려대학교 안암병원',
    lat: 37.5867,
    lng: 127.0275,
    address: '서울특별시 성북구 고려대로 73',
    phone: '02-920-5114',
    availableBeds: 10,
    totalBeds: 32,
    congestionLevel: 'medium',
    availableSpecialties: ['응급의학과', '신경외과', '정형외과', '일반외과', '신경과'],
    specialists: { '응급의학과': true, '신경외과': true, '정형외과': true, '일반외과': true, '신경과': true },
    operatingRooms: { total: 2, available: 1 },
    facilities: ['CT', 'MRI', '응급수술실'],
    isL2Registered: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'kyunghee',
    name: '경희대학교병원',
    lat: 37.5938,
    lng: 127.0508,
    address: '서울특별시 동대문구 경희대로 23',
    phone: '02-958-8114',
    availableBeds: 14,
    totalBeds: 28,
    congestionLevel: 'low',
    availableSpecialties: ['응급의학과', '정형외과', '일반외과', '신경과'],
    specialists: { '응급의학과': true, '정형외과': true, '일반외과': true, '신경과': true },
    operatingRooms: { total: 2, available: 2 },
    facilities: ['CT', 'MRI'],
    isL2Registered: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'chungang',
    name: '중앙대학교병원',
    lat: 37.5050,
    lng: 126.9575,
    address: '서울특별시 동작구 흑석로 102',
    phone: '02-6299-1114',
    availableBeds: 9,
    totalBeds: 25,
    congestionLevel: 'medium',
    availableSpecialties: ['응급의학과', '일반외과', '정형외과'],
    specialists: { '응급의학과': true, '일반외과': true, '정형외과': false },
    operatingRooms: { total: 2, available: 1 },
    facilities: ['CT', 'MRI'],
    isL2Registered: false,
    lastUpdated: new Date().toISOString(),
  },
  // ── 추가 병원 ──
  {
    id: 'snu-bundang',
    name: '분당서울대학교병원',
    lat: 37.3520,
    lng: 127.1237,
    address: '경기도 성남시 분당구 구미로173번길 82',
    phone: '031-787-7114',
    availableBeds: 20,
    totalBeds: 42,
    congestionLevel: 'low',
    availableSpecialties: ['응급의학과', '신경외과', '흉부외과', '심장내과', '정형외과', '일반외과', '신경과', '소아청소년과'],
    specialists: { '응급의학과': true, '신경외과': true, '흉부외과': true, '심장내과': true, '정형외과': true, '일반외과': true, '신경과': true, '소아청소년과': true },
    operatingRooms: { total: 4, available: 3 },
    facilities: ['CT', 'MRI', '혈관조영술', '인공심폐기', '응급수술실', '외상소생실'],
    isL2Registered: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'ajou',
    name: '아주대학교병원',
    lat: 37.2795,
    lng: 127.0463,
    address: '경기도 수원시 영통구 월드컵로 164',
    phone: '031-219-5114',
    availableBeds: 16,
    totalBeds: 35,
    congestionLevel: 'medium',
    availableSpecialties: ['응급의학과', '신경외과', '정형외과', '일반외과', '흉부외과', '성형외과'],
    specialists: { '응급의학과': true, '신경외과': true, '정형외과': true, '일반외과': true, '흉부외과': true, '성형외과': true },
    operatingRooms: { total: 3, available: 2 },
    facilities: ['CT', 'MRI', '혈관조영술', '응급수술실', '외상소생실', '화상치료실'],
    isL2Registered: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'hanyang',
    name: '한양대학교병원',
    lat: 37.5579,
    lng: 127.0427,
    address: '서울특별시 성동구 왕십리로 222-1',
    phone: '02-2290-8114',
    availableBeds: 11,
    totalBeds: 30,
    congestionLevel: 'medium',
    availableSpecialties: ['응급의학과', '심장내과', '정형외과', '일반외과', '이비인후과'],
    specialists: { '응급의학과': true, '심장내과': true, '정형외과': true, '일반외과': true, '이비인후과': true },
    operatingRooms: { total: 2, available: 1 },
    facilities: ['CT', 'MRI', '혈관조영술', '응급수술실'],
    isL2Registered: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'ewha',
    name: '이화여자대학교 목동병원',
    lat: 37.5350,
    lng: 126.8828,
    address: '서울특별시 양천구 안양천로 1071',
    phone: '02-2650-5114',
    availableBeds: 7,
    totalBeds: 22,
    congestionLevel: 'low',
    availableSpecialties: ['응급의학과', '산부인과', '소아청소년과', '일반외과'],
    specialists: { '응급의학과': true, '산부인과': true, '소아청소년과': true, '일반외과': true },
    operatingRooms: { total: 2, available: 2 },
    facilities: ['CT', 'MRI', '신생아집중치료실'],
    isL2Registered: true,
    lastUpdated: new Date().toISOString(),
  },
];
